name: Github Actions CI/CD
 
on:
  push:
    branches:
      - "main"
  
jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Dependencies for main
      run: sudo docker compose up -d --build main
